import fs from 'fs';
// eslint-disable-next-line import/no-extraneous-dependencies
import { build } from 'esbuild';

function rewriteImports() {
  return {
    name: 'rewrite-imports',
    // eslint-disable-next-line no-shadow
    setup(build) {
      // eslint-disable-next-line consistent-return
      build.onResolve({ filter: /.*/ }, (args) => {
        /* Spectrum Web Components */
        // if path is for another module, rewrite it as external
        let [entry] = build.initialOptions.entryPoints;
        ([entry] = entry.replace('./src/', '').split('.'));

        if (/@spectrum-web-components\/base/.test(args.path)) return undefined;

        if (/@spectrum-web-components/.test(args.path) && args.path.indexOf(`@spectrum-web-components/${entry}`) < 0) {
          // get the first folder after @spectrum-web-components
          const [, path] = args.path.split('/');
          return {
            path: `/libs/features/spectrum-web-components/${path}.js`,
            external: true,
          };
        }
        return undefined;
      });
    },
  };
}

const mods = fs.readdirSync('./src');

mods.forEach((mod) => {
  build({
    bundle: true,
    banner: { js: '/* Generated by Milo*/\n/* eslint-disable */' },
    entryPoints: [`./src/${mod}`],
    format: 'esm',
    sourcemap: false,
    legalComments: 'none',
    minify: true,
    plugins: [rewriteImports()],
    outfile: mod,
  });
});
